spring.application.name=Proyecto
server.port = 8090
# Config base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/Proyecto
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
#   Tambien podria ser: create, y despues usamos update
#    create-drop   crea tablas y las elimina al terminar la ejecucion

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=franciscoriquelmenunez@gmail.com
spring.mail.password=gyll ndof lnus hrja
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true