pipeline {
    agent any
    tools {
        maven "maven"
    }
    stages {
        stage("Clone Repository") {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                                userRemoteConfigs: [[url: 'https://github.com/francisco2435/Entrega-1-Tingeso']])
            }
        }

        stage("Build JAR File") {
            steps {
                dir("proyecto") {
                    bat "mvn clean install -DskipTests"
                }
            }
        }

        stage("Test") {
            steps {
                dir("proyecto") {
                    catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                        bat "mvn test"
                    }
                }
            }
        }

        stage("Build and Push Docker Image") {
            steps {
                dir("proyecto") {
                    script {
                        withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                            bat 'docker login -u "%DOCKER_USERNAME%" -p "%DOCKER_PASSWORD%" https://index.docker.io/v1/'
                            bat "docker build -t franciscoriquelmenunez/backend-container ."
                            bat "docker push franciscoriquelmenunez/backend-container "
                        }
                    }
                }
            }
        }
    }
}